default_user: nomad
packages_rns:
  - python3-pip
  - python3-setuptools
  - build-essential
  - cargo
  - python3-wheel
  - python3-pygame  
packages_build_rns:
  - python3-pil
  - libimagequant0
  - libopenjp2-7
  - libraqm0
  - libwebpdemux2
  - libwebpmux3
  - python3-setuptools-rust
  - python3-semantic-version
  - python3-typing-extensions
  - rust-all
  - python3-dev
  - libexpat1-dev
  - libjs-jquery
  - libjs-sphinxdoc
  - libjs-underscore
  - libpython3-dev
  - libpython3.10-dev
  - python3.10-dev
  - zlib1g-dev
  - libssl-dev
  - libffi-dev
  - libllvm13
  - libz3-4
  - llvm-13
  - llvm-13-linker-tools
  - llvm-13-runtime
  - libgl1-mesa-dev
  - libegl-dev
  - libgl-dev
  - libgles-dev
  - libgles1
  - libgles2
  - libglvnd-core-dev
  - libglvnd-dev
  - libglx-dev
  - libopengl-dev
  - libpthread-stubs0-dev
  - libssh2-1
  - libstd-rust-1.66
  - libx11-dev
  - libxau-dev
  - libxcb1-dev
  - libxdmcp-dev
  - llvm-15
  - llvm-15-linker-tools
  - llvm-15-runtime
  - rust-clippy
  - rust-gdb
  - rustfmt
  - x11proto-dev
  - xorg-sgml-doctools
  - xtrans-dev
packages_sdr:
  - rtl-sdr
  - gqrx-sdr
packages_osmocom:
  - extrepo
packages_lokinet:
  - lokinet-gui
  - libuv1
packages_signalserver_gui:
  - python3-pip-whl
  - python3-setuptools-whl
  - python3.10-venv
packages_build_signalserver:
  - ghc
  - libbsd-dev
  - libbz2-dev
  - libghc-bzlib-dev
  - libgmp-dev
  - libgmpxx4ldbl
  - libllvm11
  - libmd-dev
  - libncurses-dev
  - llvm-11
  - llvm-11-linker-tools
  - llvm-11-runtime
packages_qflipper:
  - libqt5quickcontrols2-5
  - libqt5qml5
  - libqt5qmlmodels5
  - libqt5quick5
  - libqt5quicktemplates2-5
  - qml-module-qtquick-window2
  - qml-module-qt-labs-platform
  - qml-module-qtqml-models2
  - qml-module-qtquick-controls
  - qml-module-qtquick-layouts
  - qml-module-qtquick-controls2
  - qml-module-qtquick-templates2
  - libqt5qmlworkerscript5
  - qml-module-qtgraphicaleffects
  - qml-module-qtqml
  - qml-module-qtquick2
  - libqt5svg5
packages_js8call:
  - libgstreamer-gl1.0-0
  - libqt5multimedia5-plugins
  - libqt5multimediagsttools5
  - libqt5multimediawidgets5
packages_build:
  - autoconf
  - automake
  - autotools-dev
  - clang
  - clang-14
  - cmake
  - cmake-data
  - dh-elpa-helper
  - emacsen-common
  - file
  - gcc-10-base
  - gfortran
  - gfortran-11
  - libarchive13
  - libclang-common-14-dev
  - libclang-cpp14
  - libclang1-14
  - libgc1
  - libgcc-10-dev
  - libgfortran-10-dev
  - libgfortran-11-dev
  - libjsoncpp25
  - libllvm14
  - libmagic-mgc
  - libmagic1
  - libobjc-11-dev
  - libobjc4
  - libqt5multimediaquick5
  - librhash0
  - libsigsegv2
  - libtext-unidecode-perl
  - libtool
  - libudev-dev
  - libusb-1.0-0-dev
  - libxml-libxml-perl
  - libxml-namespacesupport-perl
  - libxml-sax-base-perl
  - libxml-sax-perl
  - llvm-14-linker-tools
  - m4
  - qtmultimedia5-dev
  - tex-common
  - texinfo
  - libqt5serialport5-dev
  - libfftw3-dev
  - libpulse-dev
  - libasound2-dev
  - libkf5pulseaudioqt-dev
  - libqt5quickparticles5
  - libqt5quickshapes5
  - libqt5quicktest5
  - libqt5quickwidgets5
  - libqt5waylandclient5
  - libqt5waylandclient5-dev
  - libqt5waylandcompositor5
  - qt5-qmltooling-plugins
  - qtdeclarative5-dev
  - qtdeclarative5-dev-tools
  - qtquickcontrols2-5-dev
  - qtwayland5
  - qtwayland5-dev-tools
  - libqt5svg5-dev
  - libhyphen0
  - libqt5designer5
  - libqt5designercomponents5
  - libqt5help5
  - libqt5positioning5
  - libqt5sensors5
  - libqt5sql5-sqlite
  - libqt5webchannel5
  - libqt5webkit5
  - libwoff1
  - libxslt1.1
  - qdoc-qt5
  - qhelpgenerator-qt5
  - qt5-assistant
  - qtattributionsscanner-qt5
  - qttools5-dev-tools
  - gfortran-13
  - libblkid-dev
  - libclang-common-16-dev
  - libclang-cpp16
  - libclang1-15
  - libclang1-16
  - libgfortran-13-dev
  - libglib2.0-dev
  - libglib2.0-dev-bin
  - libkf5pulseaudioqt3
  - libllvm16
  - libmount-dev
  - libpcre2-32-0
  - libpcre2-dev
  - libpcre2-posix3
  - libpkgconf3
  - libselinux1-dev
  - libsepol-dev
  - llvm-16-linker-tools
  - pkg-config
  - pkgconf
  - pkgconf-bin
  - texinfo-lib
  - uuid-dev
  - libglu1-mesa-dev
  - libqt5concurrent5
  - libqt5sql5
  - libqt5test5
  - libvulkan-dev
  - libvulkan1
  - libxext-dev
  - qt5-qmake
  - qt5-qmake-bin
  - qtbase5-dev-tools
packages_console:
  - iw
  - tcpdump
  - git
  - iptables
  - nftables
  - bridge-utils
  - vim
  - btrfs-progs
  - armbian-config
  - screen
packages_desktop:
  - wireshark
  - libxkbcommon-x11-0
  - xsel
  - fonts-roboto
  - lightdm-gtk-greeter
  - lightdm-gtk-greeter-settings
  - xfonts-base
  - tightvncserver
  - x11vnc
  - xorg
  - lightdm
  - xfce4
  - tango-icon-theme
  - gnome-icon-theme
  - dbus-x11
  - chromium-browser
  - webext-ublock-origin-chromium
packages_services:
  - firewalld
  - i2pd
  - pulseaudio
  - pavucontrol
  - soundmodem
  - direwolf
packages_qtsoundmodem:
  - libqt5serialport5
  - qterm
packages_build_qtsoundmodem:
  - qtbase5-dev
