default_user: nomad
packages_rns:
  - libgl1-mesa-dev
  - python3-pip
  - python3-setuptools
  - build-essential
  - python3-dev
  - libffi-dev
  - cargo
  - libssl-dev
  - python3-wheel
  - rust-all
  - python3-setuptools-rust
  - python3-pil
  - python3-pygame  
packages_sdr:
  - rtl-sdr
  - gqrx-sdr
packages_osmocom:
  - extrepo
packages_console:
  - iw
  - tcpdump
  - git
  - iptables
  - nftables
  - bridge-utils
  - vim
  - btrfs-progs
  - armbian-config
  - screen
packages_desktop:
  - wireshark
  - libxkbcommon-x11-0
  - xsel
  - fonts-roboto
  - lightdm-gtk-greeter
  - lightdm-gtk-greeter-settings
  - xfonts-base
  - tightvncserver
  - x11vnc
  - xorg
  - lightdm
  - xfce4
  - tango-icon-theme
  - gnome-icon-theme
  - dbus-x11
packages_services:
  - firewalld
  - i2pd
  - pulseaudio
  - pavucontrol
  - soundmodem
  - direwolf
