- name: Install RNS and tools
  hosts: localhost
  tasks:
  - name: Ping my hosts
    ansible.builtin.ping:
  - name: Print message
    ansible.builtin.debug:
      msg: Installing RNS and Tools Modules
  - name: Install RNS Required Build Packages
    ansible.builtin.apt:
      pkg:
        "{{ packages_build_rns }}"
  - name: Install RNS and tools 
    ansible.builtin.command: /usr/bin/pip3 install rns lxmf nomadnet requests sbapp
    become: yes
    become_user: "{{ default_user }}"
    args:
      chdir: /home/{{ default_user }}
  - name: Create "{{ '/home' + default_user + '/.local/share/applications'}}" directory if it does not exist
    ansible.builtin.file:
      path: /home/{{ default_user }}/.local/share/applications
      state: directory
      owner: "{{ default_user }}"
      group: users
      mode: '0755'
  - name: Copy NomadNet.desktop to "{{ '/home' + default_user + '/.local/share/applications'}}"
    ansible.builtin.copy:
      src: ../config/user/orangepi3-lts/default/desktop/NomadNet.desktop
      dest: /home/{{ default_user }}/.local/share/applications/
      owner: "{{ default_user }}"
      group: users
      mode: '0755'
      backup: yes
  - name: Copy Sideband.desktop to "{{ '/home' + default_user + '/.local/share/applications'}}"
    ansible.builtin.copy:
      src: ../config/user/orangepi3-lts/default/desktop/Sideband.desktop
      dest: /home/{{ default_user }}/.local/share/applications/Sideband.desktop
      owner: "{{ default_user }}"
      group: users
      mode: '0755'
      backup: yes
  - name: Create "{{ '/home' + default_user + '/.local/share/icons'}}" directory if it does not exist
    ansible.builtin.file:
      path: /home/{{ default_user }}/.local/share/icons
      state: directory
      owner: "{{ default_user }}"
      group: users
      mode: '0755'
  - name: Copy sideband.png to "{{ '/home' + default_user + '/.local/share/icons'}}"
    ansible.builtin.copy:
      src: ../config/user/orangepi3-lts/default/desktop/sideband.png
      dest: /home/{{ default_user }}/.local/share/icons/sideband.png
      owner: "{{ default_user }}"
      group: users
      mode: '0755'
      backup: yes
  - name: Copy reticulum.png to "{{ '/home' + default_user + '/.local/share/icons'}}"
    ansible.builtin.copy:
      src: ../config/user/orangepi3-lts/default/desktop/reticulum.png
      dest: /home/{{ default_user }}/.local/share/icons/reticulum.png
      owner: "{{ default_user }}"
      group: users
      mode: '0755'
      backup: yes
