- name: Copy rns user config
  hosts: localhost
  vars:
    default_user: nomad
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:
   - name: Print message
     ansible.builtin.debug:
       msg: Copying rns user config
   - name: Copy reticulum config 
     ansible.builtin.copy:
       src: config_user/orangepi3-lts/default/rns/reticulum.config
       dest: /home/{{ default_user }}/.reticulum/config
       owner: "{{ default_user }}"
       group: users 
       mode: '0644'
       backup: yes
   - name: Copy NomadNet config 
     ansible.builtin.copy:
       src: config_user/orangepi3-lts/default/rns/nomadnet.config 
       dest: /home/{{ default_user }}/.nomadnetwork/config
       owner: "{{ default_user }}"
       group: users 
       mode: '0644'
       backup: yes
   - name: Copy Node index page 
     ansible.builtin.copy:
       src: config_user/orangepi3-lts/default/rns/index.mu 
       dest: /home/{{ default_user }}/.nomadnetwork/storage/pages/index.mu
       owner: "{{ default_user }}"
       group: users 
       mode: '0644'
       backup: yes
