- name: Copy rns user config
  hosts: localhost
  tasks:
  - name: Ping my hosts
    ansible.builtin.ping:
  - name: Print message
    ansible.builtin.debug:
      msg: Copying rns user config
  - name: Create ~/.reticulum directory if it does not exist
    ansible.builtin.file:
      path: /home/{{ default_user }}/.reticulum
      state: directory
      owner: "{{ default_user }}"
      group: users
      mode: '0755'
  - name: Copy reticulum config
    ansible.builtin.copy:
      src: ../config/user/orangepi3-lts/default/rns/reticulum.config
      dest: /home/{{ default_user }}/.reticulum/config
      owner: "{{ default_user }}"
      group: users
      mode: '0644'
      backup: yes
  - name: Create ~/.nomadnetwork directory if it does not exist
    ansible.builtin.file:
      path: /home/{{ default_user }}/.nomadnetwork
      state: directory
      owner: "{{ default_user }}"
      group: users
      mode: '0755'
  - name: Copy NomadNet config
    ansible.builtin.copy:
      src: ../config/user/orangepi3-lts/default/rns/nomadnet.config
      dest: /home/{{ default_user }}/.nomadnetwork/config
      owner: "{{ default_user }}"
      group: users
      mode: '0644'
      backup: yes
  - name: Create ~/.nomadnetwork/storage/pages directory if it does not exist
    ansible.builtin.file:
      path: /home/{{ default_user }}/.nomadnetwork/storage/pages
      state: directory
      owner: "{{ default_user }}"
      group: users
      mode: '0755'
  - name: Copy Node index page
    ansible.builtin.copy:
      src: ../config/user/orangepi3-lts/default/rns/index.mu
      dest: /home/{{ default_user }}/.nomadnetwork/storage/pages/index.mu
      owner: "{{ default_user }}"
      group: users
      mode: '0644'
      backup: yes
