- name: Copy vnc service file and speedup 
  hosts: localhost
  tasks:
  - name: Ping my hosts
    ansible.builtin.ping:
  - name: Print message
    ansible.builtin.debug:
      msg: Copying vnc systemd service file and speedup script
  - name: Copy vnc systemd service file 
    ansible.builtin.copy:
      src: ../config/system/orangepi3-lts/default/vnc/x11vnc@.service 
      dest: /etc/systemd/system/x11vnc@.service
      owner: root 
      group: root 
      mode: '0644'
      backup: yes
  - name: Create "{{ '/home' + default_user + '/.config/autostart'}}" directory if it does not exist
    ansible.builtin.file:
      path: /home/{{ default_user }}/.config/autostart
      state: directory
      owner: "{{ default_user }}"
      group: users
      mode: '0755'
  - name: Copy vnc speedup script to "{{ '/home/' + default_user + '/.config/autostart'}}"
    ansible.builtin.copy:
      src: ../config/user/orangepi3-lts/default/vnc/x11vnc-speedup.desktop 
      dest: "{{ '/home/' + default_user + '/.config/autostart/x11vnc-speedup.desktop'}}"
      owner: "{{ default_user }}" 
      group: users
      mode: '0755'
      backup: yes
