- name: Enable rns services 
  hosts: localhost
  tasks:
  - name: Ping my hosts
    ansible.builtin.ping:
  - name: Print message
    ansible.builtin.debug:
      msg: Enabling rns services 
  - name: Enable rns service
    ansible.builtin.systemd:
      name: rnsd 
      enabled: true
      masked: no
  - name: Enable nomadnet service
    ansible.builtin.systemd:
      name: nomadnet 
      enabled: true
      masked: no
