- name: Install Desktop 
  hosts: localhost
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:
   - name: Print message
     ansible.builtin.debug:
       msg: Installing Desktop 
   - name: Install Desktop Packages
     ansible.builtin.apt:
       pkg:
         "{{ packages_desktop }}"
       update_cache: yes
   - name: Remove useless packages from the cache
     ansible.builtin.apt:
       autoclean: yes
   - name: Remove dependencies that are no longer required
     ansible.builtin.apt:
       autoremove: yes
