- name: Copy desktop config and files
  hosts: localhost
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:
   - name: Print message
     ansible.builtin.debug:
       msg: Copy desktop files and config 
   - name: Create ~/backgrounds directory if it does not yet exist
     ansible.builtin.file:
       path: /home/{{ default_user }}/backgrounds
       state: directory
       owner: "{{ default_user }}"
       group: users
       mode: '0755'
   - name: Copy desktop background image
     ansible.builtin.copy:
       src: ../config/user/orangepi3-lts/default/desktop/background_desktop.png
       dest: /home/{{ default_user }}/backgrounds/default.png
       owner: "{{ default_user }}"
       group: users
       mode: '0644'
       backup: yes
   - name: Create /usr/share/backgrounds/ directory if it does not exist
     ansible.builtin.file:
       path: /usr/share/backgrounds/lightdm-gtk-greeter
       state: directory
       owner: root
       group: root 
       mode: '0755'
   - name: Copy login background image 
     ansible.builtin.copy:
       src: ../config/user/orangepi3-lts/default/desktop/background_login.png 
       dest: /usr/share/backgrounds/lightdm-gtk-greeter/default.png
       owner: root 
       group: root 
       mode: '0644'
       backup: yes
   - name: Create ~/.config/xfce4/xfconf/xfce-perchannel-xml/ directory if it does not exist
     ansible.builtin.file:
       path: /home/{{ default_user }}/.config/xfce4/xfconf/xfce-perchannel-xml/
       state: directory
       owner: "{{ default_user }}"
       group: users
       mode: '0755'
   - name: Copy desktop config 
     ansible.builtin.copy:
       src: ../config/user/orangepi3-lts/default/desktop/xfce4-desktop.xml 
       dest: /home/{{ default_user }}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml 
       owner: "{{ default_user }}"
       group: users
       mode: '0644'
       backup: yes
