- name: Configure firewall - rns 
  hosts: localhost
  tasks:
  - name: Ping my hosts
    ansible.builtin.ping:
  - name: Print message
    ansible.builtin.debug:
      msg: Configure Firewall 
  - name: "Open port 42671/udp"
    ansible.posix.firewalld:
      port: 42671/udp
      zone: public
      permanent: true
      state: enabled
  - name: "Open port 29716/udp"
    ansible.posix.firewalld:
      port: 29716/udp
      zone: public
      permanent: true
      state: enabled
