- name: Configure firewall - vnc 
  hosts: localhost
  tasks:
  - name: Ping my hosts
    ansible.builtin.ping:
  - name: Print message
    ansible.builtin.debug:
      msg: Configure Firewall - vnc 
  - name: Open port 5900/tcp 
    ansible.posix.firewalld:
      port: 5900/tcp
      zone: public
      permanent: true
      state: enabled
