- name: Configure firewall - i2pd 
  hosts: localhost
  tasks:
  - name: Ping my hosts
    ansible.builtin.ping:
  - name: Print message
    ansible.builtin.debug:
      msg: Configure Firewall -  i2pd 
  - name: Open port 19209/udp 
    ansible.posix.firewalld:
      port: 19209/udp
      zone: public
      permanent: true
      state: enabled
  - name: Open port 19209/tcp 
    ansible.posix.firewalld:
      port: 19209/tcp
      zone: public
      permanent: true
      state: enabled
