- name: Install QTSoundmodem 
  hosts: localhost
  tasks:
  - name: Ping my hosts
    ansible.builtin.ping:
  - name: Print message
    ansible.builtin.debug:
      msg: Installing QTsoundmodem 
  - name: Install Build Requirement Packages
    ansible.builtin.apt:
      pkg:
        - qtbase5-dev
        - libqt5serialport5
        - libqt5serialport5-dev
        - libfftw3-dev
        - libpulse-dev
        - libasound2-dev
        - libkf5pulseaudioqt-dev
      update_cache: yes
  - name: Create ~/build directory if it does not exist
    ansible.builtin.file:
      path: /home/{{ default_user }}/build
      state: directory
      owner: "{{ default_user }}"
      group: users
      mode: '0755'
  - name: Download and unpack QTSoundmodem source 
    ansible.builtin.unarchive:
      src: http://www.cantab.net/users/john.wiseman/Downloads/Beta/QtSMSource.zip 
      dest: /home/{{ default_user }}/build 
      remote_src: yes
  - name: Run qmake 
    ansible.builtin.command: /usr/bin/qmake 
      become: yes
      become_user: "{{ default_user }}"
      args:
        chdir: /home/{{ default_user }}/build/QtSoundModem 
  - name: Copy QtSoundModem to /usr/local/bin 
    ansible.builtin.copy:
      src: /home/{{ default_user }}/build/QtSoundModem 
      dest: /usr/local/bin/QtSoundModem
      owner: "{{ default_user }}" 
      group: users 
      mode: '0755'
  - name: Remove useless packages from the cache
    ansible.builtin.apt:
      autoclean: yes
  - name: Remove dependencies that are no longer required
    ansible.builtin.apt:
      autoremove: yes
