- name: Install QTSoundmodem 
  hosts: localhost
  tasks:
  - name: Ping my hosts
    ansible.builtin.ping:
  - name: Print message
    ansible.builtin.debug:
      msg: Installing QTsoundmodem 
  - name: Install Build Requirement Packages
    ansible.builtin.apt:
      pkg:
        "{{ packages_build }}"
      update_cache: yes
  - name: Install QtSoundModem Build Requirement Packages
    ansible.builtin.apt:
      pkg:
        "{{ packages_build_qtsoundmodem }}"
      update_cache: yes
  - name: Install Required Packages
    ansible.builtin.apt:
      pkg:
        "{{ packages_qtsoundmodem }}"
      update_cache: yes
  - name: Create ~/build directory if it does not exist
    ansible.builtin.file:
      path: /opt/build
      state: directory
      owner: root 
      group: root 
      mode: '0755'
  - name: Download and unpack QTSoundmodem source 
    ansible.builtin.unarchive:
      src: http://www.cantab.net/users/john.wiseman/Downloads/Beta/QtSMSource.zip 
      dest: /opt/build 
      owner: root 
      group: root
      remote_src: yes
  - name: Run qmake 
    ansible.builtin.command: qmake 
    args:
        chdir: /opt/build/QtSoundModem 
  - name: Run make 
    ansible.builtin.command: make 
    args:
      chdir: /opt/build/QtSoundModem 
  - name: Run make install 
    ansible.builtin.command: make install 
    args:
      chdir: /opt/build/QtSoundModem 
  - name: Copy QtSoundmodem to /usr/local/bin 
    ansible.builtin.copy:
      src: /opt/build/QtSoundModem/QtSoundModem
      dest: /usr/local/bin/QtSoundModem 
      owner: root
      group: root
      mode: '0755'
      backup: yes
  - name: Create /usr/local/share/applications directory if it does not exist
    ansible.builtin.file:
      path: /usr/local/share/applications
      state: directory
      owner: root
      group: root
      mode: '0755'
  - name: Copy QtSoundmodem.desktop to /usr/local/share/applications 
    ansible.builtin.copy:
      src: ../config/system/orangepi3-lts/default/desktop/QtSoundModem.desktop
      dest: /usr/local/share/applications/QtSoundModem.desktop
      owner: root
      group: root
      mode: '0755'
      backup: yes
  - name: Create /usr/local/share/icons directory if it does not exist
    ansible.builtin.file:
      path: /usr/local/share/icons
      state: directory
      owner: root
      group: root
      mode: '0755'
  - name: Copy radio.png to /usr/local/share/icons
    ansible.builtin.copy:
      src: ../config/system/orangepi3-lts/default/desktop/radio.png
      dest: /usr/local/share/icons/radio.png
      owner: root
      group: root
      mode: '0644'
      backup: yes
  - name: Uninstall QtSoundModem Build Requirement Packages
    ansible.builtin.apt:
      pkg:
        "{{ packages_build_qtsoundmodem }}"
      state: absent
  - name: Remove dependencies that are no longer required
    ansible.builtin.apt:
      autoremove: yes
  - name: Remove useless packages from the cache
    ansible.builtin.apt:
      autoclean: yes
